pipeline {
    agent {
       // docker {
        //    image 'maven:3.9.0'
        //    args '-v /root/.m2:/root/.m2'
	    label 'master' 
        //}
    }
	parameters {
        choice(name: 'ENVIRONMENT', choices: ['dev', 'qa', 'prod'], description: 'Select deployment environment')
        booleanParam(name: 'RUN_TESTS', defaultValue: true, description: 'Run tests?')
    }
    stages {
        stage('Build') {
		       when {
                expression { params.RUN_TESTS == true }
            }
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
		
		    when {
                expression { params.RUN_TESTS == true }
            }
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
		            when {
                expression { params.RUN_TESTS == true }
            }
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
